I2263 - actually make it work
vimc/cached-metrics pull request #1
Opened 2018-10-09 12:47 UTC by littledice

2018-10-09 12:47 UTC, littledice commented on app/main.py
> -def seconds_elapsed_since(timestamp):
moved into submodule

2018-10-09 13:36 UTC, richfitz requested changes

2018-10-09 13:36 UTC, richfitz commented on app/main.py
> +    if since_last_backup > 60 * 10:
This should be configurable, in `config.json` perhaps as `max_age_seconds`?

2018-10-09 13:36 UTC, richfitz commented on app/main.py
> +        return status_values
Do we need to return `responding: True` here in addition to the data?

2018-10-09 13:36 UTC, richfitz commented on app/main.py
> +    labels = get_labels()
I forget how flask apps work but is it worth doing this on app startup?

2018-10-09 14:31 UTC, littledice commented
Note the more complex directory structure, with `app/app` is taken directly from the documentation of the docker image we're using: https://github.com/tiangolo/uwsgi-nginx-flask-docker#quickstart-for-bigger-projects-structured-as-a-python-package

As soon as I started adding more than one file into the app directory I ran into all sorts of problems with python module imports. Following the instructions in that README I was able to get it working both inside the main container and in the test container.

2018-10-10 08:45 UTC, richfitz requested changes

2018-10-10 08:45 UTC, richfitz commented on scripts/run
> +docker build --tag $tag .
Can we build the image on teamcity like the other images, push out to docker hub and our local registry? Or we can move this into a future ticket...

2018-10-10 08:45 UTC, richfitz commented on cache-example
> +metrics_created_at: 1539089746
So based on our slack discussions, this becomes:

```json
{
  "utc_seconds":  1539089746,
  "utc_string": "ignored",
  "data": {
    "some_metrics": 32178
  }
}
```

2018-10-10 08:45 UTC, richfitz commented on tests/test_main.py
> +def create_mock_data(timestamp):
if you update the example above, similar update here too

2018-10-10 08:45 UTC, richfitz commented on README.md
> +./scripts/teamcity.sh
The teamcity build built for me a different container than the one that `run` built - is that expected?

2018-10-10 13:26 UTC, hillalex commented on README.md
> +./scripts/teamcity.sh
yes, `run` doesn't copy tests into the container

2018-10-11 11:30 UTC, littledice commented
Tested and working with local barman running from this branch: `https://github.com/vimc/montagu-db/pull/108`

2018-10-11 13:41 UTC, MartinEden requested changes
I'm still trying to get my head around how this all fits together.

Could you add the following to the README? I think they would both be helpful in the future, and helpful for me to understand things now.

* Description of what the config file format is
* Instructions on how to run the app minimally - e.g. create a volume with a file containing some metrics, as if we'd run something like the barman cron job, and then how to point this app at that file

2018-10-11 14:00 UTC, richfitz requested changes

2018-10-11 14:00 UTC, richfitz commented on app/app/main.py
> +        ms = {"responding": False}
Should we add a `{responding: True}` to the successful branch of the `try` block?

2018-10-11 14:00 UTC, richfitz commented on scripts/run
> +
pull the image first perhaps?

2018-10-11 14:00 UTC, littledice commented
Ok, have made the README more detailed @MartinEden

2018-10-11 14:24 UTC, hillalex commented on app/app/main.py
> +        ms = {"responding": False}
That is happening but in `parse_status`, so maybe it would be clearer to move that logic here?

2018-10-11 14:25 UTC, hillalex commented on app/app/main.py
> +        ms = {"responding": False}
Ah, I see what's going on. We're using `responding: False` to indicate both that the metrics have error-red, and that the cache is stale. I'll split into 2 different metrics.

2018-10-11 14:37 UTC, MartinEden requested changes
Okay, I think I've got my head around this now, and I am happy with the code as it stands other than this one minor suggestion.

2018-10-11 14:37 UTC, MartinEden commented on scripts/run
> +    docker.montagu.dide.ic.ac.uk:5000/cached-metrics:$GIT_ID
It would be nice to echo at something like "Metrics are now being served at http://localhost:$port/metrics".

2018-10-11 15:14 UTC, richfitz approved these changes

2018-10-12 09:38 UTC, MartinEden approved these changes

2018-10-12 09:38 UTC, merged